name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              timeout-minutes: 2

            - name: Install dependencies
              run: npm install
              timeout-minutes: 10

            - name: Lint
              run: npm run lint
              timeout-minutes: 5
